### ISSUE TITLE
Saying *Nothing beats fdir* might be a little off

### ISSUE THREAD

**Issue by juanibiapina** [thecodrr/fdir#11]
https://github.com/jessegrosjean/jwalk/blob/master/benches/benchmarks.md

**Comment by thecodrr** [comment]
Sorry I think you misunderstood (not your fault). What I mean was basically this: "Nothing in the Node.js environment beats fdir in speed." not that Nothing in the whole world can beat it. I know of course native implementations like rust, C or C++ can easily overcome `fdir` in speed. I will clarify it in the README. Thanks for pointing it out.

By the way, how many files in the linux source tree? Just curious.
