### ISSUE TITLE
Add Video Hub App to "Used by" section in README

### ISSUE THREAD

**Issue by whyboris** [thecodrr/fdir#120]
🙇  thank you @thecodrr for creating and maintaining `fdir` ❤️ 

Please consider adding `whyboris/Video-Hub-App` to the list of "notable projects" that use `fdir` 😊 since it has >500 stars 🌟 

https://github.com/whyboris/Video-Hub-App 🎬 

Note that my repository for **Video Hub App** also has a [thank you section](https://github.com/whyboris/Video-Hub-App?tab=readme-ov-file#thank-you) which lists `fdir` since [2020](https://github.com/whyboris/Video-Hub-App/pull/602) 😘

**Comment by thecodrr** [comment]
@whyboris feel free to open a PR.

**Comment by whyboris** [comment]
Thank you, PR #121 ready 🤝 

ps - I love how simple to use and useful `fdir` is 🥳 I'm also using it in [utilitarianism.net](https://github.com/whyboris/utilitarianism.net) to move PDFs after generating them 😎
