### ISSUE TITLE
Resolving symlinks can result in an infinite loop

### ISSUE THREAD

**Issue by SuperchupuDev** [thecodrr/fdir#125]
If there's a directory symlink somewhere and it points into a parent directory `fdir` will enter an infinite loop. Other libraries such as `fast-glob` seem to have an upper limit to avoid this, but I haven't looked at its handling yet

**Comment by thecodrr** [comment]
Hm. I don't think this should happen at all. Setting an upper limit could work as a hotfix but we should add a proper fix that checks against this.

**Comment by thecodrr** [comment]
I think I found a solution. Putting up a PR soon for testing.

**Comment by thecodrr** [comment]
@SuperchupuDev What would be the ideal behavior if we crawl `/some/dir`:

```ts
  mock({
    "/some/dir": {
      file: "somefile",
      fileSymlink: mock.symlink({
        path: "/some/dir",
      }),
      another: mock.symlink({ path: "/some/dir/fileSymlink" }),
      another2: mock.symlink({ path: "./fileSymlink" }),
    },
  });
```

Should we crawl `/some/dir` only once? Or should we crawl it 3 times (one of each symlink)?

**Comment by thecodrr** [comment]
I tested `tree` and it does this:

```
thecodrr@DESKTOP-DS3J1G9:~$ tree -ld test/
test/
├── symdir -> /home/thecodrr/test  [recursive, not followed]
├── symsymdir -> /home/thecodrr/test/symdir  [recursive, not followed]
└── symsymsymdir -> ./symdir  [recursive, not followed]

3 directories
```

Interesting:

```
tree -l test_parent/test/
test_parent/test/
├── file
└── sym -> /home/thecodrr/test_parent
    ├── randomchild
    └── test
        ├── file
        └── sym -> /home/thecodrr/test_parent  [recursive, not followed]

3 directories, 3 files
```

If there's a symlink somewhere deep inside that points to a parent of the directory you are crawling, it gets crawled and you get 2 sets of files. However, if there are 2 symlinks that point to the same parent directory, it bails out:

```
tree -l test_parent/test/
test_parent/test/
├── file
├── sym -> /home/thecodrr/test_parent
│   ├── randomchild
│   └── test
│       ├── file
│       ├── sym -> /home/thecodrr/test_parent  [recursive, not followed]
│       └── sym2 -> /home/thecodrr/test_parent  [recursive, not followed]
└── sym2 -> /home/thecodrr/test_parent  [recursive, not followed]

5 directories, 3 files
```

The general policy being that if there are more than one symlinks pointing at the same directory, it will bail out:

```
tree -l test_parent/test/
test_parent/test/
├── file
├── sym -> /home/thecodrr/test_parent
│   ├── randomchild
│   └── test
│       ├── file
│       ├── sym -> /home/thecodrr/test_parent  [recursive, not followed]
│       ├── sym2 -> /home/thecodrr/test_parent  [recursive, not followed]
│       ├── sym3 -> /home/thecodrr/test2
│       │   └── hello
│       └── sym4 -> /home/thecodrr/test2  [recursive, not followed]
├── sym2 -> /home/thecodrr/test_parent  [recursive, not followed]
├── sym3 -> /home/thecodrr/test2  [recursive, not followed]
└── sym4 -> /home/thecodrr/test2  [recursive, not followed]

9 directories, 4 files
```

**Comment by SuperchupuDev** [comment]
> @SuperchupuDev What would be the ideal behavior if we crawl `/some/dir`:
> 
> ```ts
>   mock({
>     "/some/dir": {
>       file: "somefile",
>       fileSymlink: mock.symlink({
>         path: "/some/dir",
>       }),
>       another: mock.symlink({ path: "/some/dir/fileSymlink" }),
>       another2: mock.symlink({ path: "./fileSymlink" }),
>     },
>   });
> ```
> 
> Should we crawl `/some/dir` only once? Or should we crawl it 3 times (one time for each symlink)?

i mean the former sounds better for performance, but both sound like they would do the same in terms of what the user gets returned so i guess both work 🤷‍♀️ whatever you find better to implement

**Comment by SuperchupuDev** [comment]
hi @thecodrr, any news on this? do you need help in implementing a fix?
