### ISSUE TITLE
Regression: `maxDepth` silent crash on windows if set to less than 0

### ISSUE THREAD

**Issue by SuperchupuDev** [thecodrr/fdir#127]
I have no idea what causes this, but 6.4.1 broke tinyglobby tests on windows by throwing that in some tests. I have no idea if users are affected. Looking this issue up shows it might be related to node's test runner though

Seems to be thrown by a test that sets the `maxDepth` option, once it gets thrown node:test propagates it to all remaining tests

https://github.com/SuperchupuDev/tinyglobby/actions/runs/11371715863/job/31634407668?pr=60

EDIT: also happens outside node:test, instead of throwing an error it..doesn't run? definitely can affect users

repro code:
```js
import path from 'node:path';
import { convertPathToPattern, glob } from 'tinyglobby';

import { createFixture } from 'fs-fixture';

const fixture = await createFixture({
  a: {
    'a.txt': 'a',
    'b.txt': 'b'
  },
  b: {
    'a.txt': 'a',
    'b.txt': 'b'
  },
  '.a/a/a.txt': 'a',
  '.deep/a/a/a.txt': 'a',
  '.symlink': {
    file: ({ symlink }) => symlink('../a/a.txt'),
    dir: ({ symlink }) => symlink('../a')
  }
});

const cwd = fixture.path;

console.log('a', cwd);

const a = await glob({ patterns: ['.deep/a/a/*.txt'], deep: 2, cwd });

console.log('hi', a); // this doesn't ever get logged for some reason

await fixture.rm();
```

**Comment by SuperchupuDev** [comment]
as a complete guess when early debugging it might be related to this:
![image](https://github.com/user-attachments/assets/fe7f50f6-6b2e-45e4-892b-868c730a5b97)

**Comment by thecodrr** [comment]
Can't reproduce it.

**Comment by SuperchupuDev** [comment]
are you on windows? anyways, reverting the queue change showcased in the screenshot seems to fix it, should i send a pr?

**Comment by thecodrr** [comment]
> reverting the queue change 

That was unnecessary because as you can see, it enqueues and then immediately dequeues. Instead of that now it just returns which should be fine since there was no enqueuing.

**Comment by thecodrr** [comment]
I am on Windows btw.

**Comment by SuperchupuDev** [comment]
interesting, i'm going to try to add a repro as a failing test and will pr that for now then, it's weird because i can consistently reproduce in both my machine and `tinyglobby`'s windows ci

**Comment by thecodrr** [comment]
Ran this:

```ts
const assert = require("node:assert");
const { fdir } = require("./dist/index");
const { test } = require("node:test");

test("test", async () => {
  await new fdir()
    .withMaxDepth(1)
    .withErrors()
    .crawl("node_modules")
    .withPromise();
});
```

And worked fine.

**Comment by SuperchupuDev** [comment]
i see that `tinyglobby` ends up passing `maxDepth` as -1, so it looks like it maybe happens when maxDepth is less than 1

**Comment by thecodrr** [comment]
Oh yes. Now I can repro it. Let me fix it.

**Comment by SuperchupuDev** [comment]
can confirm the fix works by manually changing fdir in `node_modules`. thanks for the extremely fast fix ❤️

btw, just a small patchnotes nit: you mention it happened when it's `< 1` when in reality it happens when it's `< 0`
