### ISSUE TITLE
Typescript definitions seems a bit wrong

### ISSUE THREAD

**Issue by selfrefactor** [thecodrr/fdir#14]
Thank you for this fast and useful library.

I have a problem, as VSCode is not happy that you declare that you will return `String[]` from `fdir.async` method. If it is `string[]` then the issue is no longer there.

**Comment by thecodrr** [comment]
Fixed in https://github.com/thecodrr/fdir/commit/0ec9e5515e456c516405f337225c1cad706b7e27
