### ISSUE TITLE
picomatch not found on base install

### ISSUE THREAD

**Issue by Flupster** [thecodrr/fdir#24]
I know you're actively developing this however the documentation on the readme doesn't work out of the box

it requires new fdir() not fdir.new()

also I noticed you went through and tried to add an error if they use glob, however these checks don't work and tries to load picomatch regardless which means on a simple `npm i fdir` and running `const fdir = require("fdir").default;` results in `Error: Cannot find module 'picomatch'`

Also good work on this, I would like to add an enhancement which is case insensitivity :)

**Comment by thecodrr** [comment]
@Flupster Fixed both the issues.

What do you mean by `case insensitivity`?
