### ISSUE TITLE
Typescript def seems to miss exports

### ISSUE THREAD

**Issue by Razzeee** [thecodrr/fdir#29]
As `sync` now returns `Output`, we need a way to tell the compiler which output it is.
One thing we could do is just cast `x = x as PathsOutput;` but that needs the types combined to create `Output` to be exported in the `.d.ts` file.

**Comment by thecodrr** [comment]
Yes, we can export the Output types.

I am not a TS Ninja but there might be some better way to automatically resolve this based on what flags are on. Open to any suggestions.
