### ISSUE TITLE
fdir is not a constructor

### ISSUE THREAD

**Issue by itesainnovation** [thecodrr/fdir#37]
Hi there!

I'm getting this error while trying to create a new builder. Any ideas what's going on?

Thanks

**Comment by thecodrr** [comment]
Can you please show your code?

**Comment by martinvanwieringen** [comment]
I am getting the same error:

Your sample code:
const fdir = require("fdir").default;

// create the builder
const api = new fdir().withFullPaths().crawl("path/to/dir");

// get all files in a directory synchronously
const files = api.sync();

// or asynchronously
api.withPromise().then((files) => {
  // do something with the result here.
  console.log();
});

**Comment by thecodrr** [comment]
@martinvanwieringen 

I think there was no need for `require("fdir").default`. Try with: `const fdir = require("fdir")`.

**Comment by itesainnovation** [comment]
> @martinvanwieringen
> 
> I think there was no need for `require("fdir").default`. Try with: `const fdir = require("fdir")`.

Exactly, it's fixed by not requiring default

**Comment by chalkygames123** [comment]
The type definition also seems to have the inconsistency.

<img width="705" alt="スクリーンショット 2020-07-27 15 42 34" src="https://user-images.githubusercontent.com/5608239/88511879-8f4de880-d020-11ea-9208-324771014117.png">

<img width="704" alt="スクリーンショット 2020-07-27 15 43 11" src="https://user-images.githubusercontent.com/5608239/88511888-92e16f80-d020-11ea-9031-65e5e8c13e3e.png">

**Comment by thecodrr** [comment]
@chalkygames123 fixing it right away

**Comment by pl4yradam** [comment]
`import fdir from 'fdir';`

`const crawler: any = new fdir()
            .withBasePath()
            .filter((fPath) => fPath.endsWith('.exe'));

 const exes = [...crawler.crawl(folders[i].location).sync()];`

Same issue

**Comment by thecodrr** [comment]
Apparently, `export default` doesn't work nicely with `require` so I had to migrate to using named imports. I have updated the documentation and README accordingly, please refer to that.
