### ISSUE TITLE
Feature Request: cwd option

### ISSUE THREAD

**Issue by ozum** [thecodrr/fdir#51]
Hi,

Assuming current cwd is `/Users/user/Development/project`, `crawl("src/target")` returns:

`withFullPaths()`: `/Users/user/Development/project/src/target/a/b/c`,
`withBasePath()`: `src/target/a/b/c`,

It would be very nice to have one of the following:

- `withRelativePath()`: `a/b/c`
- `withRelativePath("src")`: `target/a/b/c`.

Thanks,

**Comment by DominikLevitsky** [comment]
+1

**Comment by thecodrr** [comment]
I will look into this for sure.
