### ISSUE TITLE
File has no extension, can not found 

### ISSUE THREAD

**Issue by zhangdaren** [thecodrr/fdir#65]
like glob, can not found.

**Comment by thecodrr** [comment]
Hey, please add some code and tell me what's the issue. I can't fix anything with 5 words as information.

**Comment by broofa** [comment]
Pro-tip: Issues like this... just add the "more info needed" label and close immediately.

If/when OP follows up (which doesn't happen more often than not) you can decide whether to reopen.

**Comment by thecodrr** [comment]
@broofa good idea.
