### ISSUE TITLE
Adjust readme a bit

### ISSUE THREAD

**Issue by Leland-Kwong** [thecodrr/fdir#7]
I have a pretty thick skin, and I like that you're pushing the envelope with performance here. You seem like a really smart guy, but the usage of the words *shit* come off a bit crass. Just my opinion, take it or leave it 😄.

**Comment by thecodrr** [comment]
Hahaha. Well, it is supposed to be a bit casual/informal. I have read readmes that read like an essay. Too boring. Besides, relatively s**t is the least offensive word in the bad words dictionary. No offense intended of course to anyone. Thanks for taking the interest. Really appreciate it.
