### ISSUE TITLE
Invalid reference of TypeScript types

### ISSUE THREAD

**Issue by k7sleeper** [thecodrr/fdir#88]
Type definitions are now located under `dist`. Thus, field `types` in `package.json` must have the value `"dist/index.d.ts"`,

**Comment by thecodrr** [comment]
Oops. I missed this. Thanks for the heads up. I'll release a version right away.

**Comment by thecodrr** [comment]
[v6.0.1](https://www.npmjs.com/package/fdir) is out that fixes this.
