### ISSUE TITLE
Add `fs.readdir` with `{ recursive: true }` to benchmarks

### ISSUE THREAD

**Issue by isker** [thecodrr/fdir#95]
As of node 20.1.0 and 18.17.0, there is now a recursive implementation of `fs.readdirSync`, `fs.promises.readdir`, etc: https://nodejs.org/api/fs.html#fspromisesreaddirpath-options.  It would be good to have fdir benchmarked against it.

It's trivial to add, and I did so locally (don't worry, the performance of these functions is quite poor 🌞), but I figure there's no point in opening a PR as my machine is quite different from the one used in the existing BENCHMARKS.md.

**Comment by thecodrr** [comment]
@isker would you be williing to open a PR for it?

**Comment by isker** [comment]
Well, like I said, I could add the benchmark, but I'd probably need you to actually run it? You have the machine that produced BENCHMARKS.md, right?

**Comment by thecodrr** [comment]
@isker oh right. Sorry morning brain is a little slow 😆 . I will add this to the benchmarks soon.

**Comment by thecodrr** [comment]
Done.

**Comment by isker** [comment]
Thank you!
